#! /bin/bash

if [ "$UID" -ne 0 ]; then
	echo "Must be root, exiting."
else
	aptitude -Vy install openbox openbox-themes tint2 \
		conky xcompmgr volumeicon-alsa xscreensaver \
		xscreensaver-gl feh parcellite network-manager-gnome
fi
